"""create entries

Revision ID: b151f9728af6
Revises: 
Create Date: 2026-02-02 00:14:33.231778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b151f9728af6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hanzi', sa.String(length=64), nullable=False),
    sa.Column('pinyin', sa.String(length=128), nullable=True),
    sa.Column('ru', sa.Text(), nullable=False),
    sa.Column('pos', sa.String(length=32), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entries_hanzi', 'entries', ['hanzi'], unique=False)
    op.create_index('ix_entries_pinyin', 'entries', ['pinyin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_pinyin', table_name='entries')
    op.drop_index('ix_entries_hanzi', table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
